# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/CLA_top.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/CLAgen_4bit.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/add_half.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/voting_machine/voting_machine.srcs/sources_1/new/bcd_to_7seg.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/voting_machine/voting_machine.srcs/sources_1/new/clk_gen.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/voting_machine/voting_machine.srcs/sources_1/new/led_mux.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/my_xor.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/sum_to_2_bcd.v}
  {C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/sources_1/new/cla_adder_7seg.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/constrs_1/new/CLA_FPGA.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Nick Schiffer/Documents/School/CMPE125/Labs/cla_adder_7seg/cla_adder_7seg.srcs/constrs_1/new/CLA_FPGA.xdc}}]


synth_design -top cla_adder_7seg -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cla_adder_7seg.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cla_adder_7seg_utilization_synth.rpt -pb cla_adder_7seg_utilization_synth.pb"
